### ISSUE TITLE
Bayesian correlation NaN in Renv nightly

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jaspRegression#29]
**Analysis issue link (if applicable):**

**Operating system:**
Mac OS 10.14.6

**Commit ID:**
Nightly https://github.com/jasp-stats/jasp-desktop/commit/5273a5d47770371970d74ffd717b07504e5f49e8

**JASP file / screenshot:**

**Bug description**
- Bayesian correlation results are all NaN.
- I think that there's an overkill on https://github.com/jasp-stats/jaspRegression/commit/e7bc8242d39dadd83eb67e1a9dd80221860c25f3

**Steps to reproduce**

**Expected behaviour**

**Comment by AlexanderLyNL** [comment]
@Kucharssim could you check whether this is also the case for you?

**Comment by Kucharssim** [comment]
Yeah, I can reproduce with the latest renv nightly on Mac, but not on development. Maybe this arises due to some differences in `bstats` in `development` and `renv`? I would check that out but I cannot say I exactly understand how is renv set up...

**Comment by AlexanderLyNL** [comment]
No need to check this. We'll test this again closer to release to exclude renv problems. I'm glad it works on development, that's the main thing at the moment.

**Comment by AlexanderLyNL** [comment]
Fixed in the new R4.1 nightly: https://github.com/jasp-stats/jasp-desktop/commit/50daf61093f684833b292c935c42d733cf5064c2

Of course this needs testing before releasing.
